Repository MrKai77/Loop, pull requests merged in 2024-07, with the labels that each got.

#492 ✨ Update indicator
  Loop.xcodeproj/project.pbxproj
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AboutConfiguration.swift
  Loop/Luminare/LuminareManager.swift
Labels: Improvement

#493 ✨ iCloud sync
  Loop.xcodeproj/project.pbxproj
  Loop/AppDelegate.swift
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Info.plist
  Loop/Loop.entitlements
Labels: Feature

#484 ✨ Wallpaper color theming
  Loop.xcodeproj/project.pbxproj
  Loop/Assets.xcassets/Nucleo/18px_image-depth.imageset/18px_image-depth.pdf
  Loop/Assets.xcassets/Nucleo/18px_image-depth.imageset/Contents.json
  Loop/Extensions/Color+Extensions.swift
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AdvancedConfiguration.swift
  Loop/Luminare/Loop/ExcludedAppsConfiguration.swift
  Loop/Luminare/Settings/Behavior/BehaviorConfiguration.swift
  Loop/Luminare/Theming/AccentColorConfiguration.swift
  Loop/Luminare/Theming/PreviewConfiguration.swift
  Loop/Luminare/Theming/WallpaperColors.swift
  Loop/Managers/LoopManager.swift
  Loop/Managers/WindowDragManager.swift
  Loop/Preview Window/PreviewView.swift
  Loop/Updater/UpdateView.swift
Labels: Feature

#498 ✨ Ability to ignore fullscreen windows
  Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AdvancedConfiguration.swift
  Loop/Managers/LoopManager.swift
Labels: Feature

#499 🌐 Improve localization process
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AboutConfiguration.swift
  Loop/Luminare/Settings/Behavior/BehaviorConfiguration.swift
  Loop/Luminare/Settings/Keybindings/CustomActionConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/Keybind Recorder/Keycorder.swift
  Loop/Luminare/Settings/Keybindings/KeybindingsConfiguration.swift
  Loop/Luminare/Theming/AccentColorConfiguration.swift
  Loop/Luminare/Theming/IconConfiguration.swift
  Loop/Updater/UpdateView.swift
  Loop/Window Management/Custom Window Sizes/CustomWindowActionUnit.swift
Labels: Localization

#506 ✨ Ability to advance cycles with a left click
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Managers/LoopManager.swift
  Loop/Window Management/WindowAction.swift
Labels: Feature

#511 🌐 Updated localizations for Chinese (Simplified), Chinese (Hong Kong) and Spanish
  Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AboutConfiguration.swift
  Loop/Luminare/Theming/IconConfiguration.swift
Labels: Localization

#512 🌐 Updated localization
  Loop/Localizable.xcstrings
Labels: Localization

#514 🌐 Updated Portuguese (Brazil) localization
  Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
  Loop/Localizable.xcstrings
  Loop/Radial Menu/RadialMenuView.swift
Labels: Localization
