Repository MrKai77/Loop, pull requests merged in 2024-12, with the labels that each got.

#646 ✨ Keybind import/export/reset improvements
  Loop/Extensions/Notification+Extensions.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AdvancedConfiguration.swift
  Loop/Luminare/Settings/Keybindings/KeybindItemView.swift
  Loop/Utilities/RectangleTranslationLayer.swift
  Loop/Window Management/WindowAction+Port.swift
Labels: Improvement

#647 🐞 Don't record every single step of cycle when preview is disabled
  Loop/Extensions/Notification+Extensions.swift
  Loop/Luminare/Theming/IconConfiguration.swift
  Loop/Managers/LoopManager.swift
  Loop/Window Management/WindowEngine.swift
  Loop/Window Management/WindowRecords.swift
Labels: Bug

#655 🌐 Update localizations from Crowdin + Improve wording
  Loop/Assets.xcassets/Credits/kai.imageset/68963405.png
  Loop/Assets.xcassets/Credits/kai.imageset/Contents.json
  Loop/Assets.xcassets/Credits/kai.imageset/kai.jpg
  Loop/Localizable.xcstrings
  Loop/Luminare/Settings/Behavior/BehaviorConfiguration.swift
Labels: Localization

#656 🐞 Fix memory leak in `NSEventMonitor`
  Loop/Utilities/EventMonitor.swift
Labels: Bug
