Repository MrKai77/Loop, pull requests merged in 2024-11, with the labels that each got.

#605 ✨ Add Maximize Height & Width
  Loop/Localizable.xcstrings
  Loop/Utilities/RectangleTranslationLayer.swift
  Loop/Window Management/WindowAction+Image.swift
  Loop/Window Management/WindowAction.swift
  Loop/Window Management/WindowDirection+LocalizedString.swift
  Loop/Window Management/WindowDirection.swift
Labels: Feature

#612 ✨ Remove padding limit of 200 pt
  Loop/Luminare/Settings/Behavior/Padding Configuration/PaddingConfigurationView.swift
  Loop/Window Management/WindowAction.swift
Labels: Improvement

#613 🐞 Show gradient toggle even when using system accent color
  Loop/Luminare/Theming/AccentColorConfiguration.swift
Labels: Bug
