Repository MrKai77/Loop, pull requests merged in 2025-09, with the labels that each got.

#806 ✨ Increase Stage Manager strip size range, fix clamping
  Loop/Luminare/Loop/AdvancedConfiguration.swift
  Loop/Luminare/Settings/Behavior/BehaviorConfiguration.swift
  Loop/Luminare/Settings/Behavior/Padding Configuration/PaddingConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/CustomActionConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/KeybindsConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/StashActionConfigurationView.swift
  Loop/Luminare/Theming/PreviewConfiguration.swift
  Loop/Luminare/Theming/RadialMenuConfiguration.swift
Labels: Improvement

#802 ✨ Trigger key improvements, remove usage of notifications throughout codebase
  Loop/Extensions/Notification+Extensions.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AdvancedConfiguration.swift
  Loop/Luminare/LuminareManager.swift
  Loop/Luminare/Settings/Keybindings/KeybindItemView.swift
  Loop/Luminare/Settings/Keybindings/Modal Views/CustomActionConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/Modal Views/CycleActionConfigurationView.swift
  Loop/Luminare/Settings/Keybindings/Modal Views/StashActionConfigurationView.swift
  Loop/Managers/KeybindMonitor.swift
  Loop/Managers/LoopManager.swift
  Loop/Managers/StashManager/StashManager.swift
  Loop/Managers/Triggers/TriggerKeyObserver.swift
  Loop/Managers/WindowDragManager.swift
  Loop/Radial Menu/RadialMenuView.swift
  Loop/Utilities/EventMonitor.swift
  Loop/Utilities/Migrator.swift
  Loop/Utilities/Searchable Popover Picker/CustomTextField.swift
  Loop/Utilities/Searchable Popover Picker/PopoverPicker.swift
  Loop/Window Action Indicators/Preview Window/LuminarePreviewView.swift
  Loop/Window Action Indicators/Preview Window/PreviewController.swift
  Loop/Window Action Indicators/Preview Window/PreviewStartingPosition.swift
  Loop/Window Action Indicators/Preview Window/PreviewView.swift
  Loop/Window Action Indicators/Radial Menu/DirectionSelectorCircleSegment.swift
  Loop/Window Action Indicators/Radial Menu/DirectionSelectorSquareSegment.swift
  Loop/Window Action Indicators/Radial Menu/RadialMenuController.swift
  Loop/Window Action Indicators/Radial Menu/RadialMenuView.swift
  Loop/Window Action Indicators/Radial Menu/RadialMenuViewModel.swift
  Loop/Window Management/Custom Window Sizes/CustomWindowActionAnchor.swift
  Loop/Window Management/WindowAction+Image.swift
  Loop/Window Management/WindowAction.swift
  Loop/Window Management/WindowDirection+LocalizedString.swift
  Loop/Window Management/WindowEngine.swift
Labels: Feature, Improvement

#810 💄 Liquid glass icons for `AppIcon-Classic` and `AppIcon-Developer`
  .github/workflows/dev-build.yml
  Loop/AppDelegate.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/LuminareManager.swift
  Loop/Luminare/Theming/IconConfiguration.swift
  Loop/Managers/IconManager.swift
  Loop/Utilities/Icon.swift
Labels: Feature

#797 ✨ Add a "Minimize others" action
  Loop/Localizable.xcstrings
  Loop/Window Management/WindowAction+Image.swift
  Loop/Window Management/WindowDirection+LocalizedString.swift
  Loop/Window Management/WindowDirection.swift
  Loop/Window Management/WindowEngine.swift
Labels: Feature

#812 🐞 Match window frame before initializing `Window`
  Loop/Window Management/Window.swift
  Loop/Window Management/WindowEngine.swift
Labels: Bug

#814 ✨ Introduce AccentColorController
  Loop.xcodeproj/project.pbxproj
  Loop.xcodeproj/xcshareddata/xcschemes/Loop (GH ACTIONS).xcscheme
  Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
  Loop/Accent Color/AccentColorController.swift
  Loop/Accent Color/AccentColorOption.swift
  Loop/Accent Color/WallpaperImageFetcher.swift
  Loop/Accent Color/WallpaperProcessor.swift
  Loop/App/AppDelegate.swift
  Loop/App/DataPatcher.swift
  Loop/Core/LoopManager.swift
  Loop/Core/WindowDragManager.swift
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Extensions/NSColor+Extensions.swift
  Loop/Settings Window/LuminareManager.swift
  Loop/Settings Window/Settings/Keybindings/Modal Views/CustomActionConfigurationView.swift
  Loop/Settings Window/Settings/Keybindings/Modal Views/StashActionConfigurationView.swift
  Loop/Settings Window/Theming/AccentColorConfiguration.swift
  Loop/Window Action Indicators/Preview Window/LuminarePreviewView.swift
  Loop/Window Action Indicators/Preview Window/PreviewView.swift
  Loop/Window Action Indicators/Radial Menu/RadialMenuView.swift
  Loop/Window Action Indicators/Radial Menu/RadialMenuViewModel.swift
Labels: Improvement
