Repository MrKai77/Loop, pull requests merged in 2025-01, with the labels that each got.

#660 🐞 Bug fixes
  Loop.xcodeproj/project.pbxproj
  Loop/Luminare/Settings/Keybindings/Keybind Recorder/Keycorder.swift
  Loop/Managers/LoopManager.swift
  Loop/Utilities/EventMonitor.swift
  Loop/Window Management/Window.swift
Labels: Bug

#674 📝 Fix "Resize Adjacent Windows" item in comparison chart
  README.md
Labels: Improvement

#675 🔧 Refactor key modifier handling in Keycorder
  Loop/Luminare/Settings/Keybindings/Keybind Recorder/Keycorder.swift
Labels: Bug

#676 ✨ Disable update checks via variables
  Loop.xcodeproj/project.pbxproj
  Loop.xcodeproj/xcshareddata/xcschemes/Loop.xcscheme
  Loop/Extensions/Defaults+Extensions.swift
  Loop/Localizable.xcstrings
  Loop/Luminare/Loop/AboutConfiguration.swift
  Loop/Updater/Updater.swift
Labels: Feature, Improvement

#677 🐞 Move window activation to after minimizing/hiding
  Loop/Window Management/WindowEngine.swift
Labels: Bug
